version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: npm run start
    stdin_open: true
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/app/src

  api:
    command: npm run dev
    volumes:
      - ./api/src:/app/src

  auth:
    command: npm run dev
    volumes:
      - ./auth/src:/app/src

  nginx:
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
